// This file provides a static list of popular movie, TV, and person names for random search bar placeholder suggestions.
export const SEARCH_SUGGESTIONS = [
  "Breaking Bad",
  "Inception",
  "Game of Thrones",
  "Stranger Things",
  "The Godfather",
  "La Casa de Papel",
  "Friends",
  "Interstellar",
  "Fight Club",
  "The Dark Knight",
  "Pulp Fiction",
  "Seinfeld",
  "Cillian Murphy",
  "Margot Robbie",
  "Barbie",
  "Oppenheimer",
  "The Office",
  "Peaky Blinders",
  "Avatar",
  "Titanic",
  "Brad Pitt",
  "Leonardo DiCaprio",
  "Scarlett Johansson",
  "The Matrix",
  "Lost",
  "Sherlock Holmes",
  "Narcos",
  "The Crown",
  "The Mandalorian",
  "Wednesday",
  "The Queen's Gambit"
];
